import requests


arr0=[
["ENGG 501","Computational Mathematics 1" , "core", "Master of Science in Computer Engineering", 3],
["ENGG 502", "Computational Mathematics 2" , "core", "Master of Science in Computer Engineering", 3],
["ENGG 503", "Design of Experiments and Data Analytics " , "core", "Master of Science in Computer Engineering", 3],
["ENGG 504","Applied Materials Science and Engineering", "major", "Master of Science in Computer Engineering", 3],
["MCpE 501","VLSI Circuit Design with HDL", "major", "Master of Science in Computer Engineering", 3],
["MCpE 502","Microprocessor Design and FPGA", "major", "Master of Science in Computer Engineering", 3],
["MCpE 503","Distributed Computer Systems", "major", "Master of Science in Computer Engineering", 3],
["MCpE 504","High Performance & Parallel Computer Architectures", "major", "Master of Science in Computer Engineering", 3],
["MCpE 505","Wireless Networks", "major", "Master of Science in Computer Engineering", 3],
["MCpE 506","Artificial Intelligence with Python", "elective", "Master of Science in Computer Engineering", 3],
["MCpE 507","Advanced Broadband Communication Systems", "elective", "Master of Science in Computer Engineering", 3],
["MCpE 509","Computer Networks and Security", "elective", "Master of Science in Computer Engineering", 3],
["MCpE 511","Fuzzy Logic", "elective", "Master of Science in Computer Engineering", 3],
["MCpE 516","Operating System Design and Implementation", "elective", "Master of Science in Computer Engineering", 3],
["MCpE 517","Advanced Software Engineering", "elective", "Master of Science in Computer Engineering", 3],
["MCpE 519","Advanced Computer Architecture", "elective", "Master of Science in Computer Engineering", 3],
["GECE 517","Machine Learning", "elective", "Master of Science in Computer Engineering", 3],
["GECE 518","Neural Networks", "elective", "Master of Science in Computer Engineering", 3],
["MCpE 520","Seminars in Thesis Writing in Computer Engineering", "thesis", "Master of Science in Computer Engineering", 3],
["MCpE 521","Thesis Writing in Computer Engineering", "thesis", "Master of Science in Computer Engineering", 3],
]

arr1=[
["ENGG 501","Computational Mathematics 1", "foundation", "Straight Master's-Doctoral in Electronics Engineering", 3],
["ENGG 502","Computational Mathematics 2","foundation", "Straight Master's-Doctoral in Electronics Engineering", 3],
["ENGG 503","Design of Experiments and Data Analytics", "foundation", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 501","Linear Systems Theory","major","Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 502","Modern Control Theory and Applications","major","Straight Master's-Doctoral in Electronics Engineering", 3],
["ENGG 504","Applied Materials Science and Engineering", "major", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 503","Management of Technology", "specialization", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 504","Advanced Digital Signal Processing", "specialization", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 506","Advanced Electromagnetic Theory", "specialization", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 510","Digital Control", "specialization", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 512","Nonlinear Systems", "specialization", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 513","Optimal Control", "specialization", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 515","Artificial Intelligence for Cyber-Physical Systems", "specialization", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 517","Machine Learning", "specialization", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 518","Neural Networks", "specialization", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 519","Advanced Analog Design", "specialization", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 520","Advanced Digital Design", "specialization", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 521","Mixed-Signal Design", "specialization", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 507","Optical Fiber Communications", "elective", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 508","Special Topics in Communications", "elective", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 509","Adaptive Control", "elective", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 511","Multivariable Control System", "elective", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 514","Advanced Image Processing", "elective", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 516","Data Mining", "elective", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 522","Special Topics in Electronics", "elective", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 523","Special Topics in Systems and Control", "elective", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 524","Flat Antenna Design", "elective", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 525","Numerical Electromagnetics", "elective", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 526","Hilbert Space Method and Applications", "elective", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 527","Robotics and Automation", "elective", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 528","High Performance & Parallel Computer", "elective", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 529","Architectures Hyperspectral Data Processing", "elective", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 530","Low Power System Design", "elective", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 531","System-On-Chip Design", "elective", "Straight Master's-Doctoral in Electronics Engineering", 3],
["GECE 603","Dissertation 1", "dissertation", "Straight Master's-Doctoral in Electronics Engineering", 6],
["GECE 604","Dissertation 2", "dissertation", "Straight Master's-Doctoral in Electronics Engineering", 6],
]

arr2=[
["GEM 501", "Design of Experiments","core", "Doctor Of Philosophy in Engineering Management", 3],
["GEM 502", "Research Methods for Engineering Management","core", "Doctor Of Philosophy in Engineering Management", 3],
["GEM 503", "Advanced Project Management and Strategic Leadership", "core", "Doctor Of Philosophy in Engineering Management", 3],
["GEM 504", "Optimization I", "specialization", "Doctor Of Philosophy in Engineering Management", 3],
["GEM 505", "Optimization II", "specialization", "Doctor Of Philosophy in Engineering Management", 3],
["GEM 506", "Systems Analysis and Advanced Modeling", "specialization", "Doctor Of Philosophy in Engineering Management", 3],
["Course Code 1", "Course Title 1", "elective", "Doctor Of Philosophy in Engineering Management", 3],
["Course Code 2", "Course Title 2", "elective", "Doctor Of Philosophy in Engineering Management", 3],
["Compre", "Comprehensive Examination", "major", "Doctor Of Philosophy in Engineerin Management", 3 ],
["GEM 512","dissertation Writing I", "dissertation", "Doctor Of Philosophy in Engineering Management", 6],
["GEM 513","dissertation Writing II", "dissertation", "Doctor Of Philosophy in Engineering Management", 6],
]

arr3=[ 
["DPEE 501", "Foundations of Engineering Education", "core", "Doctor Of Philosophy in Engineering Education", 3],
["DPEE 502", "Research Methodology in Engineering Education", "core", "Doctor Of Philosophy in Engineering Education", 3],
["DPEE 503", "Theories of Development and Engineering Thinking", "core", "Doctor Of Philosophy in Engineering Education", 3],
["DPEE 504", "Educational Methods in Engineering Education", "core", "Doctor Of Philosophy in Engineering Education", 3],
["DPEE 505", "Developing an Engineering Education Curriculum", "specialization", "Doctor Of Philosophy in Engineering Education", 3],
["DPEE 506", "Engineering Education Practicum I", "specialization", "Doctor Of Philosophy in Engineering Education", 3],
["DPEE 507", "Engineering Education Practicum II", "specialization", "Doctor Of Philosophy in Engineering Education", 3],
["Course Code 1", "Course Title 1", "elective", "Doctor Of Philosophy in Engineering Education", 3],
["Course Code 2", "Course Title 2", "elective", "Doctor Of Philosophy in Engineering Education", 3],
["Course Code 3", "Course Title 3", "elective", "Doctor Of Philosophy in Engineering Education", 3],
["Compre", "Comprehensive Examination", "major", "Doctor Of Philosophy in Engineering Education",3],
["DPEE 508","dissertation Research I", "dissertation", "Doctor Of Philosophy in Engineering Education", 6],
["DPEE 509","dissertation Research II", "dissertation", "Doctor Of Philosophy in Engineering Education", 6],   
]

arr4=[
["ENGG 501","Computational Mathematics 1", "core", "Master of Science in Transportation Engineering", 3],
["ENGG 502","Computational Mathematics 2", "core", "Master of Science in Transportation Engineering", 3],
["MSRM 501","Research Methodology", "core", "Master of Science in Transportation Engineering", 3],
["MSTE 501","Traffic Flow Theory and Analysis", "specialization", "Master of Science in Transportation Engineering", 3],
["MSTE 502","Transportation Systems Analysis and Planning", "specialization", "Master of Science in Transportation Engineering", 3],
["MSTE 504","Planning and Design of Transportation Facilities", "specialization", "Master of Science in Transportation Engineering", 3],
["Course Code 1", "Course Title 1", "elective", "Master of Science in Transportation Engineering", 3],
["Course Code 2", "Course Title 2", "elective", "Master of Science in Transportation Engineering", 3],
["Compre", "Comprehensive Examination", "major", "Master of Science in Transportation Engineering", 3],
["MSTE 522", "Thesis 1", "thesis", "Master of Science in Transportation Engineering", 3],
["MSTE 522", "Thesis 2", "thesis", "Master of Science in Transportation Engineering", 3],
]

arr5=[
["ENGG 501","Computational Mathematics 1", "core", "Master of Science in Material Science and Engineering", 3],
["ENGG 502","Computational Mathematics 2", "core", "Master of Science in Material Science and Engineering", 3],
["ENGG 503","Design of Experiments and Data Analytics", "core", "Master of Science in Material Science and Engineering", 3],
["MMSE 501","Fundamentals of Materials Science and Engineering", "specialization", "Master of Science in Material Science and Engineering", 3],
["MMSE 502","Thermodynamics of Materials", "specialization", "Master of Science in Material Science and Engineering", 3],
["MMSE 503","Crystallography and Diffraction", "specialization", "Master of Science in Material Science and Engineering", 3],
["Course Code 1", "Course Title 1", "elective", "Master of Science in Material Science and Engineering", 3],
["Course Code 2", "Course Title 2", "elective", "Master of Science in Material Science and Engineering", 3],
["MMSE 512","Thesis 1", "thesis", "Master of Science in Material Science and Engineering", 3],
["MMSE 513","Thesis 2", "thesis", "Master of Science in Material Science and Engineering", 3],
]

arr6=[
["ENGG 501","Computational Mathematics 1", "core","Master of Science in Energy Engineering", 3],
["ENGG 502","Computational Mathematics 2","core","Master of Science in Energy Engineering", 3],
["MSRM 501","Research Methodology", "core","Master of Science in Energy Engineering", 3],
["MSEnE 511","Bioenergy Engineering", "specialization","Master of Science in Energy Engineering", 3],
["MSEnE 512","Solar Energy Engineering", "specialization","Master of Science in Energy Engineering", 3],
["MSEnE 513","Wind, Hydro and Ocean Energy Conversion System", "specialization","Master of Science in Energy Engineering", 3],
["MSEnE 501","Energy Management", "elective","Master of Science in Energy Engineering", 3],
["MSEnE 502","Energy Technology Assessment", "elective","Master of Science in Energy Engineering", 3],
["MSEnE 503","Design and Simulation of Energy System", "elective","Master of Science in Energy Engineering", 3],
["MSEnE 504","Waste Heat Recovery and Cogeneration", "elective","Master of Science in Energy Engineering", 3],
["MSEnE 505","Energy Economics and System Evaluation", "elective","Master of Science in Energy Engineering", 3],
["MSEnE 531","Master Thesis 1", "thesis","Master of Science in Energy Engineering", 3],
["MSEnE 532","Master Thesis 2", "thesis","Master of Science in Energy Engineering", 3] ,
]

arr7=[
["ENGG 501","Computational Mathematics 1", "core", "Master of Science in Earthquake Engineering", 3],
["ENGG 502","Computational Mathematics 2", "core", "Master of Science in Earthquake Engineering", 3],
["ENGG 503","Design of Experiments and Data Analytics", "core", "Master of Science in Earthquake Engineering", 3],
["MSEAQ 501","Dynamics of Structures", "major", "Master of Science in Earthquake Engineering", 3],
["MSEAQ 502","Earthquake and Tsunami Disaster Reduction", "major", "Master of Science in Earthquake Engineering", 3],
["MSEAQ 503","Passive Control of Structure against Earthquakes", "major", "Master of Science in Earthquake Engineering", 3],
["MSEAQ 505","Geotechnical Earthquake Engineering", "elective", "Master of Science in Earthquake Engineering", 3],
["MSEAQ 506","Applied Structural Design", "elective", "Master of Science in Earthquake Engineering", 3],
["Course Code 1", "Course Title 1", "elective","Master of Science in Earthquake Engineering", 3],
["Course Code 2", "Course Title 2", "elective","Master of Science in Earthquake Engineering", 3],
["MSEAQ 507","Thesis 1", "thesis", "Master of Science in Earthquake Engineering", 3],
["MSEAQ 508","Thesis 2", "thesis", "Master of Science in Earthquake Engineering", 3],
]

arr8=[
["ENGG 501","Computational Mathematics 1", "core", "Master of Science in Advanced Manufacturing", 3],
["ENGG 502","Computational Mathematics 2", "core", "Master of Science in Advanced Manufacturing", 3],
["ENGG 503","Design of Experiments and Data Analytics", "core", "Master of Science in Advanced Manufacturing", 3],
["MSAM 501","Manufacturing Systems", "specialization", "Master of Science in Advanced Manufacturing", 3],
["MSAM 502","Design for Environment, Manufacture and Assembly", "specialization", "Master of Science in Advanced Manufacturing", 3],
["MSAM 503","Seminars in Advanced Manufacturing", "specialization", "Master of Science in Advanced Manufacturing", 3],
["Course Code 1", "Course Title 1", "elective", "Master of Science in Advanced Manufacturing", 3],
["Course Code 2", "Course Title 2", "elective", "Master of Science in Advanced Manufacturing", 3],
["MSAM 513","Thesis 1", "dissertation", "Master of Science in Advanced Manufacturing", 3],
["MSAM 514","Thesis 2", "dissertation", "Master of Science in Advanced Manufacturing", 3],
]

arr9=[
["MSEM 501","Foundations of Engineering Management", "core", "Master of Science in Engineering Management", 3],
["MSEM 502","Statistics for Engineering Management", "core", "Master of Science in Engineering Management", 3],
["MSRM 501","Research Methodology", "core", "Master of Science in Engineering Management", 3],
["MSEM 504","Integrating Ethics, Contracts and Legal Issues", "specialization", "Master of Science in Engineering Management", 3],
["MSEM 505","Project Management Fundamentals", "specialization", "Master of Science in Engineering Management", 3],
["MSEM 506","Applied Accounting and Finance for Engineering Management", "specialization", "Master of Science in Engineering Management", 3],
["MSEM 507","Quality Engineering and Management", "specialization", "Master of Science in Engineering Management", 3],
["Course Code 1", "Course Title 1", "elective", "Master of Science in Engineering Management", 3],
["Course Code 2", "Course Title 2", "elective", "Master of Science in Engineering Management", 3],
["Course Code 2", "Course Title 2", "elective", "Master of Science in Engineering Management", 3],
["MSEM 517","Thesis Writing 1", "thesis", "Master of Science in Engineering Management", 3],
["MSEM 518","Thesis Writing 2", "thesis", "Master of Science in Engineering Management", 3],
]

arr10=[
["GECE 600","Directed Studies", "specialization", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 501","Linear Systems Theory", "specialization", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 502","Modern Control Theory and Applications", "specialization", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 503","Management of Technolgy", "specialization", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 504","Advanced Digital Signal Processing", "specialization", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 505","Advanced Electromagnetic Theory", "specialization", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 506","Antennas and Radiowave Propagation", "specialization", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 510","Digital Control", "specialization", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 512","Nonlinear Systems", "specialization", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 513","Optimal Control", "specialization", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 515","Artificial Intelligence for Cyber-Physical Systems", "specialization", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 517","Machine Learning", "specialization", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 518","Neural Networks", "specialization", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 519","Advanced Analog IC Design", "specialization", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 520","Advanced Digital IC Design", "specialization", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 521","Mixed-Signal IC Design", "specialization", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 507","Optical Fiber Communications", "elective", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 508","Special Topics in Communications ", "elective", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 509","Adaptive Control", "elective", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 511","Multivariable Control System", "elective", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 514","Advanced Image Processing", "elective", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 516","Data Mining", "elective", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 522","Special Topics in Electronics", "elective", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 523","Special Topics in System and Control", "elective", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 524","Flat Antenna Design", "elective", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 525","Numerical Electromagnetics", "elective", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 526","Hilbert Space Method and Applications", "elective", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 526","Robotics and Automation", "elective", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 526","High Performance & Parallel Computer Architectures", "elective", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 526","Hyperspectral Data Processing", "elective", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 530","Low Power System Design", "elective", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 531","System-On-Chip Design", "elective", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 603","Dissertation 1", "dissertation", "Doctor of Philosophy in Electronics Engineering", 3],
["GECE 604","Dissertation 2", "dissertation", "Doctor of Philosophy in Electronics Engineering", 3],
]

arr11=[
["ENGG 501","Computational Mathematics 1", "core", "Master of Science in Electronics Engineering", 3],
["ENGG 502","Computational Mathematics 2", "core", "Master of Science in Electronics Engineering", 3],
["ENGG 503","Design of Experiments and Data Analytics", "core", "Master of Science in Electronics Engineering", 3],
["ENGG 504","Applied Materials Science and Engineering", "major", "Master of Science in Electronics Engineering", 3],
["GECE 501","Linear Systems Theory", "major", "Master of Science in Electronics Engineering", 3],
["GECE 502","Modern Control Theory and Applications", "major", "Master of Science in Electronics Engineering", 3],
["GECE 503","Management of Technology", "elective", "Master of Science in Electronics Engineering", 3],
["GECE 504","Advanced Digital Signal Processing", "elective", "Master of Science in Electronics Engineering", 3],
["GECE 505","Advanced Electromagnetic Theory", "elective", "Master of Science in Electronics Engineering", 3],
["GECE 506","Antennas and Radiowave Propagation", "elective", "Master of Science in Electronics Engineering", 3],
["GECE 507","Optical Fiber Communications", "elective", "Master of Science in Electronics Engineering", 3],
["GECE 508","Special Topics in Communications", "elective", "Master of Science in Electronics Engineering", 3],
["GECE 509","Adaptive Control", "elective", "Master of Science in Electronics Engineering", 3],
["GECE 510","Digital Control", "elective", "Master of Science in Electronics Engineering", 3],
["GECE 511","Multivariable Control System", "elective", "Master of Science in Electronics Engineering", 3],
["GECE 512","Nonlinear Systems", "elective", "Master of Science in Electronics Engineering", 3],
["GECE 513","Optimal Control", "elective", "Master of Science in Electronics Engineering", 3],
["GECE 514","Advanced Image Processing", "elective", "Master of Science in Electronics Engineering", 3],
["GECE 515","Artificial Intelligence for Cyber-physical Systems", "elective", "Master of Science in Electronics Engineering", 3],
["GECE 516","Data Mining", "elective", "Master of Science in Electronics Engineering", 3],
["GECE 517","Machine Learning", "elective", "Master of Science in Electronics Engineering", 3],
["GECE 518","Neural Networks", "elective", "Master of Science in Electronics Engineering", 3],
["GECE 519","Advanced Analog IC Design", "elective", "Master of Science in Electronics Engineering", 3],
["GECE 520","Advanced Digital IC Design", "elective", "Master of Science in Electronics Engineering", 3],
["GECE 521","Mixed-Signal IC Design", "elective", "Master of Science in Electronics Engineering", 3],
["GECE 522","Special Topics in Electronics", "elective", "Master of Science in Electronics Engineering", 3],
["GECE 523","Special Topics in Systems and Control", "elective", "Master of Science in Electronics Engineering", 3],
["Course Code 1", "Course Title 1", "elective", "Master of Science in Electronics Engineering", 3],
["Course Code 2", "Course Title 2", "elective", "Master of Science in Electronics Engineering", 3],
["GECE 601","Master’s Thesis 1", "thesis", "Master of Science in Electronics Engineering", 3],
["GECE 602","Master’s Thesis 2", "thesis", "Master of Science in Electronics Engineering", 3],
]

arr12=[
["ENGG 501","Computational Mathematics 1", "core", "Master of Engineering major in Mechanical Engineering", 3],
["ENGG 502","Computational Mathematics 2", "core", "Master of Engineering major in Mechanical Engineering", 3],
["ENGG 503","Design of Experiments and Data Analytics", "core", "Master of Engineering major in Mechanical Engineering", 3],
["ENGG 504","Applied Materials Science and Engineering", "major", "Master of Engineering major in Mechanical Engineering", 3],
["MME 501","Advanced Thermodynamics", "major", "Master of Engineering major in Mechanical Engineering", 3],
["MME 502","Advanced Heat and Mass Transfer", "major", "Master of Engineering major in Mechanical Engineering", 3],
["MME 503","Sustainable Energy Sources", "elective", "Master of Engineering major in Mechanical Engineering", 3],
["MME 504","Energy Conversion and Utilization", "elective", "Master of Engineering major in Mechanical Engineering", 3],
["MME 505","Energy Systems Modeling and Design", "elective", "Master of Engineering major in Mechanical Engineering", 3],
["MME 506","Advanced Fluid Mechanics", "elective", "Master of Engineering major in Mechanical Engineering", 3],
["MME 507","Advanced Refrigeration System", "elective", "Master of Engineering major in Mechanical Engineering", 3],
["MME 508","Advanced Airconditioning System", "elective", "Master of Engineering major in Mechanical Engineering", 3],
["MME 509","Material Failure Analysis", "elective", "Master of Engineering major in Mechanical Engineering", 3],
["MME 510","Computational Nanotechnology", "elective", "Master of Engineering major in Mechanical Engineering", 3],
["MME 511","Smart Materials", "elective", "Master of Engineering major in Mechanical Engineering", 3],
["MME 512","Biomechanics and Biomaterials", "elective", "Master of Engineering major in Mechanical Engineering", 3],
["Course Code 1", "Course Title 1", "elective", "Master of Engineering major in Mechanical Engineering", 3],
["Course Code 2", "Course Title 2", "elective", "Master of Engineering major in Mechanical Engineering", 3],
["Course Code 3", "Course Title 3", "elective", "Master of Engineering major in Mechanical Engineering", 3],
["Course Code 4", "Course Title 4", "elective", "Master of Engineering major in Mechanical Engineering", 3],
["ENGG 505","Industry - based Capstone Project 1", "capstone", "Master of Engineering major in Mechanical Engineering", 3],
["ENGG 506","Industry - based Capstone Project 2", "capstone", "Master of Engineering major in Mechanical Engineering", 3],
]

arr13=[
["ENGG 501","Computational Mathematics 1", "core", "Master of Engineering major in Industrial Engineering", 3],
["ENGG 502","Computational Mathematics 2", "core", "Master of Engineering major in Industrial Engineering", 3],
["ENGG 503","Design of Experiments and Data Analytics", "core", "Master of Engineering major in Industrial Engineering", 3],
["ENGG 504","Applied Materials Science and Engineering", "major", "Master of Engineering major in Industrial Engineering", 3],
["MIE 501","Design and Management of Workplace", "major", "Master of Engineering major in Industrial Engineering", 3],
["MIE 502","Optimization in Production Systems", "major", "Master of Engineering major in Industrial Engineering", 3],
["MIE 503","Supply Chain Management", "elective", "Master of Engineering major in Industrial Engineering", 3],
["MIE 504","Management Information System", "elective", "Master of Engineering major in Industrial Engineering", 3],
["MIE 505","Logistics Management and Services", "elective", "Master of Engineering major in Industrial Engineering", 3],
["MIE 506","Special Problems Related to Supply Chain Management", "elective", "Master of Engineering major in Industrial Engineering", 3],
["MIE 507","Strategic Planning and Management", "elective", "Master of Engineering major in Industrial Engineering", 3],
["MIE 504","Management Information System", "elective", "Master of Engineering major in Industrial Engineering", 3],
["MIE 508","Six Sigma", "elective", "Master of Engineering major in Industrial Engineering", 3],
["MIE 509","Special Problems Related to Quality Management System", "elective", "Master of Engineering major in Industrial Engineering", 3],
["Course Code 1", "Course Title 1", "elective", "Master of Engineering major in Industrial Engineering", 3],
["Course Code 2", "Course Title 2", "elective", "Master of Engineering major in Industrial Engineering", 3],
["Course Code 3", "Course Title 3", "elective", "Master of Engineering major in Industrial Engineering", 3],
["Course Code 4", "Course Title 4", "elective", "Master of Engineering major in Industrial Engineering", 3],
["ENGG 505","Industry - based Capstone Project 1", "capstone", "Master of Engineering major in Industrial Engineering", 3],
["ENGG 506","Industry - based Capstone Project 2", "capstone", "Master of Engineering major in Industrial Engineering", 3],
]

arr14=[
["ENGG 501","Computational Mathematics 1", "core", "Master of Engineering major in Environmental Engineering", 3],
["ENGG 502","Computational Mathematics 2", "core", "Master of Engineering major in Environmental Engineering", 3],
["ENGG 503","Design of Experiments and Data Analytics", "core", "Master of Engineering major in Environmental Engineering", 3],
["ENGG 504","Applied Materials Science and Engineering", "major", "Master of Engineering major in Environmental Engineering", 3],
["MEnE 501","Environmental Health Engineering", "major", "Master of Engineering major in Environmental Engineering", 3],
["MEnE 502","Industrial Waste Management", "major", "Master of Engineering major in Environmental Engineering", 3],
["MEnE 503","Trends and Innovations in Environmental Engineering", "elective", "Master of Engineering major in Environmental Engineering", 3],
["MEnE 504","Water Quality Control and Management", "elective", "Master of Engineering major in Environmental Engineering", 3],
["MEnE 505","Environmental Geotechnology", "elective", "Master of Engineering major in Environmental Engineering", 3],
["MCE 503","Urban Hydrology", "elective", "Master of Engineering major in Environmental Engineering", 3],
["MEnE 506","Indoor Air Quality Management", "elective", "Master of Engineering major in Environmental Engineering", 3],
["MEnE 507","Environmental Impact Assessment", "elective", "Master of Engineering major in Environmental Engineering", 3],
["MCE 511","Groundwater Flow and Contaminant Transport", "elective", "Master of Engineering major in Environmental Engineering", 3],
["MEnE 508","Water Resources Planning and Development", "elective", "Master of Engineering major in Environmental Engineering", 3],
["MEnE 509","Biological Treatment Process Design", "elective", "Master of Engineering major in Environmental Engineering", 3],
["Course Code 1", "Course Title 1", "elective", "Master of Engineering major in Environmental Engineering", 3],
["Course Code 2", "Course Title 2", "elective", "Master of Engineering major in Environmental Engineering", 3],
["Course Code 3", "Course Title 3", "elective", "Master of Engineering major in Environmental Engineering", 3],
["Course Code 4", "Course Title 4", "elective", "Master of Engineering major in Environmental Engineering", 3],
["ENGG 505","Industry - based Capstone Project 1", "capstone", "Master of Engineering major in Environmental Engineering", 3],
["ENGG 506","Industry - based Capstone Project 2", "capstone", "Master of Engineering major in Environmental Engineering", 3],
]

arr15=[
["ENGG 501","Computational Mathematics 1", "core", "Master of Engineering major in Electrical Engineering", 3],
["ENGG 502","Computational Mathematics 2", "core", "Master of Engineering major in Electrical Engineering", 3],
["ENGG 503","Design of Experiments and Data Analytics", "core", "Master of Engineering major in Electrical Engineering", 3],
["ENGG 504","Applied Materials Science and Engineering", "major", "Master of Engineering major in Electrical Engineering", 3],
["MEE 501","Service and Power Quality in Distribution Systems", "major", "Master of Engineering major in Electrical Engineering", 3],
["MEE 502","Overcurrent Protection of Electric Distribution Networks", "major", "Master of Engineering major in Electrical Engineering", 3],
["MEE 503","Deregulated Power System", "elective", "Master of Engineering major in Electrical Engineering", 3],
["MEE 504","Advanced Theory of Electrical Machines", "elective", "Master of Engineering major in Electrical Engineering", 3],
["MEE 505","Fault Tolerant Power Systems", "elective", "Master of Engineering major in Electrical Engineering", 3],
["MEE 506","Power Market Economics and Security", "elective", "Master of Engineering major in Electrical Engineering", 3],
["MEE 507","Computer Applications on Power Systems", "elective", "Master of Engineering major in Electrical Engineering", 3],
["MEE 508","Economic Operation and Control of Power Systems", "elective", "Master of Engineering major in Electrical Engineering", 3],
["MEE 509","Surge and Line Protection", "elective", "Master of Engineering major in Electrical Engineering", 3],
["Course Code 1", "Course Title 1", "elective", "Master of Engineering major in Electrical Engineering", 3],
["Course Code 2", "Course Title 2", "elective", "Master of Engineering major in Electrical Engineering", 3],
["Course Code 3", "Course Title 3", "elective", "Master of Engineering major in Electrical Engineering", 3],
["Course Code 4", "Course Title 4", "elective", "Master of Engineering major in Electrical Engineering", 3],
["ENGG 505","Industry - based Capstone Project 1", "capstone", "Master of Engineering major in Electrical Engineering", 3],
["ENGG 506","Industry - based Capstone Project 2", "capstone", "Master of Engineering major in Electrical Engineering", 3],
]

arr16=[
["ENGG 501","Computational Mathematics 1", "core", "Master of Engineering major in Electronics Engineering", 3],
["ENGG 502","Computational Mathematics 2", "core", "Master of Engineering major in Electronics Engineering", 3],
["ENGG 503","Design of Experiments and Data Analytics", "core", "Master of Engineering major in Electronics Engineering", 3],
["ENGG 504","Applied Materials Science and Engineering", "major", "Master of Engineering major in Electronics Engineering", 3],
["GECE 501","Linear Systems Theory", "major", "Master of Engineering major in Electronics Engineering", 3],
["GECE 502","Modern Control Theory and Applications", "major", "Master of Engineering major in Electronics Engineering", 3],
["GECE 503","Management of Technology", "elective", "Master of Engineering major in Electronics Engineering", 3],
["GECE 504","Advanced Digital Signal Processing", "elective", "Master of Engineering major in Electronics Engineering", 3],
["GECE 505","Advanced Electromagnetic Theory", "elective", "Master of Engineering major in Electronics Engineering", 3],
["GECE 508","Special Topics in Communications", "elective", "Master of Engineering major in Electronics Engineering", 3],
["GECE 510","Digital Control", "elective", "Master of Engineering major in Electronics Engineering", 3],
["GECE 512","Nonlinear Systems", "elective", "Master of Engineering major in Electronics Engineering", 3],
["GECE 514","Advanced Image Processing", "elective", "Master of Engineering major in Electronics Engineering", 3],
["GECE 515","Artificial Intelligence for Cyber-physical Systems", "elective", "Master of Engineering major in Electronics Engineering", 3],
["GECE 517","Machine Learning", "elective", "Master of Engineering major in Electronics Engineering", 3],
["GECE 518","Neural Networks", "elective", "Master of Engineering major in Electronics Engineering", 3],
["GECE 522","Special Topics in Electronics", "elective", "Master of Engineering major in Electronics Engineering", 3],
["Course Code 1", "Course Title 1", "elective", "Master of Engineering major in Electronics Engineering", 3],
["Course Code 2", "Course Title 2", "elective", "Master of Engineering major in Electronics Engineering", 3],
["Course Code 3", "Course Title 3", "elective", "Master of Engineering major in Electronics Engineering", 3],
["Course Code 4", "Course Title 4", "elective", "Master of Engineering major in Electronics Engineering", 3],
["ENGG 505","Industry - based Capstone Project 1", "capstone", "Master of Engineering major in Electronics Engineering", 3],
["ENGG 506","Industry - based Capstone Project 2", "capstone", "Master of Engineering major in Electronics Engineering", 3],
]

arr17=[
["ENGG 501","Computational Mathematics 1", "core", "Master of Engineering major in Chemical Engineering", 3],
["ENGG 502","Computational Mathematics 2", "core", "Master of Engineering major in Chemical Engineering", 3],
["ENGG 503","Design of Experiments and Data Analytics", "core", "Master of Engineering major in Chemical Engineering", 3],
["ENGG 504","Applied Materials Science and Engineering", "major", "Master of Engineering major in Chemical Engineering", 3],
["MChE 502","Advanced Chemical Reaction Engineering", "major", "Master of Engineering major in Chemical Engineering", 3],
["MChE 503","Trends in Petrochemical Engineering", "elective", "Master of Engineering major in Chemical Engineering", 3],
["MChE 504","Polymer Engineering", "elective", "Master of Engineering major in Chemical Engineering", 3],
["MChE 505","Plastic Technology", "elective", "Master of Engineering major in Chemical Engineering", 3],
["MChE 506","Petroleum Engineering", "elective", "Master of Engineering major in Chemical Engineering", 3],
["MChE 507","Enzyme Technology", "elective", "Master of Engineering major in Chemical Engineering", 3],
["MChE 508","Molecular Biology", "elective", "Master of Engineering major in Chemical Engineering", 3],
["MChE 509","Biochemical Engineering", "elective", "Master of Engineering major in Chemical Engineering", 3],
["MChE 510","Biomass Technology", "elective", "Master of Engineering major in Chemical Engineering", 3],
["MChE 511","Renewable Energy Technologies", "elective", "Master of Engineering major in Chemical Engineering", 3],
["MChE 512","Water and Wastewater Management Technology", "elective", "Master of Engineering major in Chemical Engineering", 3],
["MChE 513","Hazardous Waste Management", "elective", "Master of Engineering major in Chemical Engineering", 3],
["MChE 514","Air Pollution Control", "elective", "Master of Engineering major in Chemical Engineering", 3],
["Course Code 1", "Course Title 1", "elective", "Master of Engineering major in Chemical Engineering", 3],
["Course Code 2", "Course Title 2", "elective", "Master of Engineering major in Chemical Engineering", 3],
["Course Code 3", "Course Title 3", "elective", "Master of Engineering major in Chemical Engineering", 3],
["Course Code 4", "Course Title 4", "elective", "Master of Engineering major in Chemical Engineering", 3],
["ENGG 505","Industry - based Capstone Project 1", "capstone", "Master of Engineering major in Chemical Engineering", 3],
["ENGG 506","Industry - based Capstone Project 2", "capstone", "Master of Engineering major in Chemical Engineering", 3],
]

arr18=[
["ENGG 501","Computational Mathematics 1", "core", "Master of Engineering major in Civil Engineering", 3],
["ENGG 502","Computational Mathematics 2", "core", "Master of Engineering major in Civil Engineering", 3],
["ENGG 503","Design of Experiments and Data Analytics", "core", "Master of Engineering major in Civil Engineering", 3],
["ENGG 504","Applied Materials Science and Engineering", "major", "Master of Engineering major in Civil Engineering", 3],
["MCE 501","Finite Element Methods in Civil Engineering", "major", "Master of Engineering major in Civil Engineering", 3],
["MCE 502","Technology and Innovation in Construction and Project Management", "major", "Master of Engineering major in Civil Engineering", 3],
["MCE 503","Urban Hydrology", "elective", "Master of Engineering major in Civil Engineering", 3],
["MCE 504","Water Supply Distribution and Treatment Design", "elective", "Master of Engineering major in Civil Engineering", 3],
["MCE 505","Design of Pavement System", "elective", "Master of Engineering major in Civil Engineering", 3],
["MCE 506","Transportation Systems Analysis and Planning", "elective", "Master of Engineering major in Civil Engineering", 3],
["MCE 507","Environmental Benefits and Costs in Civil Engineering Projects", "elective", "Master of Engineering major in Civil Engineering", 3],
["MCE 508","Matrix of Theory of Structures", "elective", "Master of Engineering major in Civil Engineering", 3],
["MCE 509","Prestressed Concrete Design and Applications", "elective", "Master of Engineering major in Civil Engineering", 3],
["MCE 510","Ground Improvement Techniques", "elective", "Master of Engineering major in Civil Engineering", 3],
["MCE 511","Groundwater Flow and Contaminant Transport", "elective", "Master of Engineering major in Civil Engineering", 3],
["MCE 512","Geotechnical Testing and Instrumentation (Laboratory)", "elective", "Master of Engineering major in Civil Engineering", 3],
["Course Code 1", "Course Title 1", "elective", "Master of Engineering major in Civil Engineering", 3],
["Course Code 2", "Course Title 2", "elective", "Master of Engineering major in Civil Engineering", 3],
["Course Code 3", "Course Title 3", "elective", "Master of Engineering major in Civil Engineering", 3],
["Course Code 4", "Course Title 4", "elective", "Master of Engineering major in Civil Engineering", 3],
["ENGG 505","Industry - based Capstone Project 1", "capstone", "Master of Engineering major in Civil Engineering", 3],
["ENGG 506","Industry - based Capstone Project 2", "capstone", "Master of Engineering major in Civil Engineering", 3],
]

arr19=[
["MSCS111","Advanced Data Structures and Algorithms", "core", "Master of Science in Computer Science", 3],
["MSCS112","Advanced Computer Organization and Operating Systems", "core", "Master of Science in Computer Science", 3],
["MSCS113","Theory of Programming Languages", "core", "Master of Science in Computer Science", 3],
["MSCS114","Theory of Computation", "core", "Master of Science in Computer Science", 3],
["MSCS211","Intelligence Systems", "specialization", "Master of Science in Computer Science", 3],
["MSCS212","Theoretical Computer Science", "specialization", "Master of Science in Computer Science", 3],
["MSCS213","Computational Science", "specialization", "Master of Science in Computer Science", 3],
["MSCS214","Data Science", "specialization", "Master of Science in Computer Science", 3],
["MSCS215","Advanced Data Security", "specialization", "Master of Science in Computer Science", 3],
["MSCS311","Thesis 1", "thesis", "Master of Science in Computer Science", 3],
["MSCS312","Thesis 2", "thesis", "Master of Science in Computer Science", 3],
]

arr20=[
["MSDS 500","Fundamentals of Data Science", "core", "Master of Science in Data Science", 3],
["MSDS 501","Big Data and Cloud Computing", "core", "Master of Science in Data Science", 3],
["MSDS 502","Data Visualization and Storytelling", "core", "Master of Science in Data Science", 3],
["MSDS 503","Machine Learning and Neural Networks", "specialization", "Master of Science in Data Science", 3],
["MSDS 504","Mathematical and Computational Theories for Data Science", "specialization", "Master of Science in Data Science", 3],
["MSDS 505","Seminars in Data Science", "specialization", "Master of Science in Data Science", 3],
["MSDS 506","Industry Internship", "elective", "Master of Science in Data Science", 3],
["MSDS 507","Data Privacy and Ethical Practice for Data Science", "elective", "Master of Science in Data Science", 3],
["MSDS 508","Biomedical Modeling for Health Data", "elective", "Master of Science in Data Science", 3],
["MSDS 509","Health Informatics", "elective", "Master of Science in Data Science", 3],
["MSDS 510","Business Economics and Strategies", "elective", "Master of Science in Data Science", 3],
["MSDS 511","Time-Series Data Analysis and Forecasting for Business and Finance", "elective", "Master of Science in Data Science", 3],
["MSDS 512","Computation and Complexity", "elective", "Master of Science in Data Science", 3],
["MSDS 513","High Performance Computing", "elective", "Master of Science in Data Science", 3],
["MSDS 514","Advance Statistical Models and Methods for Data Science", "elective", "Master of Science in Data Science", 3],
["MSDS 515","Cross-Platform Applications Design and Development", "elective", "Master of Science in Data Science", 3],
["Course Code 1", "Special Topics in Data Science 1", "elective", "Master of Science in Data Science", 3],
["Course Code 2", "Special Topics in Data Science 2", "elective", "Master of Science in Data Science", 3],
["Course Code 1", "Course Title 1", "elective", "Master of Science in Data Science", 3],
["Course Code 2", "Courese Title 2", "elective", "Master of Science in Data Science", 3],
["MSDS 520","Thesis 1", "thesis", "Master of Science in Data Science", 3],
["MSDS 521","Thesis 2", "thesis", "Master of Science in Data Science", 3],
]

arr21=[
["MITC111","Advanced Database Systems", "core", "Master in Information Technology", 3],
["MITC112","Advanced Operating Systems and Networking", "core", "Master in Information Technology", 3],
["MITC113","Advanced Systems Design and Implementation", "core", "Master in Information Technology", 3],
["MITC114","Technology and Project Management", "core", "Master in Information Technology", 3],
["MITS111","Data Science", "specialization", "Master in Information Technology", 3],
["MITS112","Data Mining", "specialization", "Master in Information Technology", 3],
["MITS113","Machine Learning", "specialization", "Master in Information Technology", 3],
["MITS114","Advance Data Security", "specialization", "Master in Information Technology", 3],
["MITS115","IOT Technology Applications", "specialization", "Master in Information Technology", 3],
["MITS116","IOT Programming", "specialization", "Master in Information Technology", 3],
["MITO111","Master's Capstone Project 1", "capstone", "Master in Information Technology", 3],
["MITO112","Master's Capstone Project 2", "capstone", "Master in Information Technology", 3],
]

arr22=[
["MOT 501","Technological Research Methodology", "core", "Master of Technology", 3],
["MOT 502","Philosophy of Technology", "core", "Master of Technology", 3],
["MOT 503","Nanotechnology", "major", "Master of Technology", 3],
["MOT 504","Environmental Technology for Sustainable Development", "major", "Master of Technology", 3],
["MOT 505","Artificial Inteligence and Machine Learning Applications", "major", "Master of Technology", 3],
["MOT 506","Telecommunications Technology", "major", "Master of Technology", 3],
["MOT 507","Strategic Management of Technology", "elective", "Master of Technology", 3],
["MOT 508","Information Security and Technology Controls", "elective", "Master of Technology", 3],
["MOT 509","Special Topics in Technology Management", "elective", "Master of Technology", 3],
["MOT 510","Global Technology Issues", "elective", "Master of Technology", 3],
["MOT 511","Advanced Manufacturing Technology", "elective", "Master of Technology", 3],
["MOT 512","Seminar in Thesis Writing", "thesis", "Master of Technology", 3],
["MOT 513","Thesis Writing", "thesis", "Master of Technology", 3],
]

arr23=[
["DOT 601","Legal Bases and Prodecures Technology", "core", "Doctor of Technology", 3],
["DOT 602","Modern Technology Trends in Data Analysis", "core", "Doctor of Technology", 3],
["DOT 603","Technology Leadership and Innovation Management", "core", "Doctor of Technology", 3],
["DOT 604","Advanced Engineering Design in Area of specialization", "major", "Doctor of Technology", 3],
["DOT 605","Advanced Product Planning and Development", "major", "Doctor of Technology", 3],
["DOT 606","Artificial Inteligence of Technology Development", "major", "Doctor of Technology", 3],
["DOT 607","Renewable Energy and Green Technology", "elective", "Doctor of Technology", 3],
["DOT 608","Environmental Control Strategies", "elective", "Doctor of Technology", 3],
["DOT 609","Global Perspectives on Emerging Technologies", "elective", "Doctor of Technology", 3],
["DOT 610","Advanced Strategic Planning and Management", "elective", "Doctor of Technology", 3],
["DOT 611","dissertation Writing I", "dissertation", "Doctor of Technology", 6],
["DOT 612","dissertation Writing II", "dissertation", "Doctor of Technology" ,6]
]


arr24=[
["MSCM 501", "Special Topics in Mathematics with Applications to Construction Management", "core", "Master of Science in Construction Management", 3],
["MSCM 502", "Optimization Methods on Construction Management", "core", "Master of Science in Construction Management", 3],
["MSCM 503", "Research Methods in Construction Management", "core", "Master of Science in Construction Management", 3],
["MSCM 504", "Construction Operations and Engineering Management", "specialization", "Master of Science in Construction Management", 3],
["MSCM 505", "Project Cost Management and Estimating", "specialization", "Master of Science in Construction Management", 3],
["MSCM 506", "Construction Scheduling and Resource Optimization", "specialization", "Master of Science in Construction Management", 3],
["Course Code1", "Course Title1", "elective", "Master of Science in Construction Management", 3],
["Course Code2", "Course Title2", "elective", "Master of Science in Construction Management", 3],
["MSCM 520", "Thesis Proposal Writing with Oral Defense", "thesis", "Master of Science in Construction Management", 3],
["MSCM 503", "Final Oral Defense", "thesis", "Master of Science in Construction Management", 3],
]

arrays = [ arr0, arr1, arr2, arr3, arr4, arr5, arr6, arr7, arr8, arr9, arr10, arr11, arr12, 
          arr13, arr14, arr15, arr16, arr17, arr18, arr19, arr20, arr21, arr22, arr23, arr24]

for i in arrays:
    for y in i:
        print (i, y)
        data = {"course_code": y[0], "course_title": y[1],
                "degree": y[3], "units": y[4], "course_type": y[2]}
        response = requests.post("http://localhost:3001/api/v1/course/create", json=data)
        if response.status_code == 200:
            print("**Success")
        else:
            print("**Failed", data)
