import React, { useEffect, useState } from "react";
import Header from "./components/header";
import axios from "axios";
import Taker from "./components/Taker";

function Admin() {
  const [takers, setTakers] = useState([]);

  useEffect(() => {
    console.log(takers);
  }, [takers]);
  useEffect(() => {
    const fetchTakers = async () => {
      try {
        const response = await axios.get(
          "http://127.0.0.1:3001/api/v1/user/admin/all"
        );
        if (response.status === 200) {
          const takers = response.data.data;
          const counts = {};
          takers.forEach((course) => {
            const count = { available: false };
            if (Object.keys(counts).includes(course.course_code)) {
              counts[course.course_code].count += 1;
              if (counts[course.course_code].count >= 5) {
                counts[course.course_code].available = true;
              }
            } else {
              count.course_title = course.course_title;
              count.count = 1;
              counts[course.course_code] = count;
            }
            console.log(count);
          });
          setTakers(counts);
        }
      } catch (err) {
        console.error(err);
      }
    };
    fetchTakers();
  }, []);

  return (
    <div className="w-full min-h-screen flex flex-col items-center gap-4">
      <Header />
      <div className="w-[95%] bg-[#C21B1B] h-[120px] font-semibold text-white flex items-center justify-center text-[20px]">
        <h1>POS GENERATION FOR ALANGILAN GRADUATE SCHOOL</h1>
      </div>
      <div className="w-full px-10">
        <h1>Available Courses</h1>
        <p>
          Courses listed below are generated by our system. For inquiries,
          please contact registrar/admin.
        </p>
      </div>
      <div className="mt-[30px] flex flex-col h-[400px] overflow-y-auto mb-[60px]">
        {Object.keys(takers).map((code) => {
          return (
            // <div className="flex gap-10">
            //   <h1 className="w-[100px]">{code}</h1>
            //   <h1 className="w-[500px]">{takers[code].course_title}</h1>
            //   <h1 className="w-[100px]">{takers[code].count}</h1>
            //   <h1 className="w-[100px]">{takers[code].available ? "Green": "Red"}</h1>
            // </div>
            <Taker takers={takers} code={code}/>
          );
        })}
      </div>
    </div>
  );
}

export default Admin;
